### PR TITLE
Adding open graph message

### PR DESCRIPTION
**Pull request by gedeagas**
Adding open graph message

### CODE REVIEW

**Comment by DiegoRBaquero** [comment]
Hi @gedeagas, looks good!

Did you happen to test it?

**Comment by gedeagas** [comment]
Hi @DiegoRBaquero since this update, I have added the Airline Boarding Pass, Airline Checkin, Airline Itinerary and Airline Flight Update but not yet pushed. I will test all the function today and as soon as the test is complete I will inform you again 😀

**Comment by DiegoRBaquero** [comment]
Alright, looking forward to it :)

**Comment by natterstefan** [comment]
Hello @gedeagas @DiegoRBaquero, do you have any news for this PR? :)

**Comment by gedeagas** [comment]
Sorry guys I totally forget about this PR.
I will update this ASAP

**Comment by DiegoRBaquero** [comment]
@gedeagas Awesome, looking forward to it

**Pull request closed without merging**
