### PR TITLE
Added List Template

### PR DESCRIPTION
**Pull request by agathaftrindade**

### CODE REVIEW

**Comment by DiegoRBaquero** [comment]
Hi! Thanks for the PR. I'm no longer maintaining this.

Would you like to maintain it?

**Comment by agathaftrindade** [comment]
Yeah, sure! I would love to.
But I think I will need some help setting up the NPM package.

**Comment by DiegoRBaquero** [comment]
what's your npm user? I'll add it.

**Comment by agathaftrindade** [comment]
@rainsongr
Thanks

**Comment by DiegoRBaquero** [comment]
Added you, you may now publish. You can do so by doing `npm version minor` and `npm publish`. This will generate a tag, please push with `git push --tags` to have a release con github too.

**Pull request merged**
